version: '3.8'
services:
  mysql:
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 4000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - mysql_network

  php:
    build: ./php
    volumes:
      - ./php/httpd.conf:/etc/apache2/mods-enabled/httpd.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    ports:
      - 8080:80
      - 8000:8000
      - 5173:5173
    depends_on:
      - mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
